# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/TECNO/Hentai-Heaven/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),Hentai-Heaven)

$(call add-radio-file-sha1-checked,radio/gz.img,bce720a7c30532b108e523863c520c0460fabf62)
$(call add-radio-file-sha1-checked,radio/lk.img,d01cb05a97438fff44d7cedf8d380099281bb674)
$(call add-radio-file-sha1-checked,radio/logo.img,1dc145b4086ebd614a9a7dc4162b8608e07f7c7d)
$(call add-radio-file-sha1-checked,radio/md1img.img,802a54eef988900eb854ece488320279fd52a8bb)
$(call add-radio-file-sha1-checked,radio/preloader.img,44ff00a28ac49fba4fa0c113f775830b2d776689)
$(call add-radio-file-sha1-checked,radio/scp.img,2b1dee8ba4a60b52e431678b50ce0de12bf87688)
$(call add-radio-file-sha1-checked,radio/spmfw.img,87474aeb44ac0e5fa5c241e223cd7bb86d8f7f02)
$(call add-radio-file-sha1-checked,radio/sspm.img,60be5418c19e0cc9cb4666a4723bed394a8f81c7)
$(call add-radio-file-sha1-checked,radio/tee.img,cf949669f55cd368e80f4258c76d22fc6f12152e)
$(call add-radio-file-sha1-checked,radio/tranfs.img,fec714db6f483678b4b2e87034644353b2a6d832)
$(call add-radio-file-sha1-checked,radio/tkv.img,e949411583a8165fe3862fe067ae485ffe043bdb)

endif
