# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/TECNO/Hentai-Heaven/setup-makefiles.sh

AB_OTA_PARTITIONS += \
    gz \
    lk \
    logo \
    md1img \
    preloader \
    scp \
    spmfw \
    sspm \
    tee \
    tkv \
    tranfs